name: NPM Publish
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v2
        with:
          node-version: 16.13.0
          registry-url: 'https://registry.npmjs.org'
      - run: yarn install --immutable --immutable-cache
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM }}
